### ISSUE TITLE
TODO before 1.0

### ISSUE THREAD

**Issue by sormuras** [sormuras/listing#1]
- [x] clean up `java.lang.reflect` factory methods
- [x] add `JavaType.toClassName` support
- [x] add in-memory compilation support using `javax.tools.JavaCompiler`
- [x] add `javax.lang.model` factory methods #3
- [x] re-implement `unit` package
- [x] import-aware `Name` emission
- [x] simple demo snippet for README.md
- [ ] javadoc

**Comment by PiIntelligence** [comment]
Concerning javax.lang.model factory methods issue:

Won't the following snippet do the job just fine ?

`static JavaType<?> of(TypeMirror m) {
        if (m == null) return null;
        return JavaType.of(m.getKind().getDeclaringClass());
    }`

**Comment by sormuras** [comment]
No, that won't do. See https://github.com/sormuras/listing/issues/3 for an outline and some details.

**Comment by sormuras** [comment]
https://github.com/sormuras/listing/milestone/1 took over.
