### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sormuras** [sormuras/listing#1]
- [ ] add members: field, method w/ parameter(s)
- [ ] consider some immutables like `TypeName`, `ClassType` or `Annotation`
- [ ] add java.lang.reflect factories
- [ ] add javax.lang.model factories
